sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f ./client.Dockerfile.dev ./client 

script:
  - docker run docker-react npm test -- --coverage

after_success:
  - docker build -t multi-react ./client
  - docker build -t multi-nginx ./nginx
  - docker build -t multi-server ./server
  - docker build -t multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin # echo $password is retrieve travis env variable and input to docker login login to docker hub to push image publicly
  - docker push multi-react
  - docker push multi-nginx
  - docker push multi-server
  - docker push multi-worker